/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <LCD.h>
#include <Pin_button_aliases.h>
#include <Pin_button.h>
#include <inter_button.h>
#include <PWM.h>
#include <Pin_motor_aliases.h>
#include <Pin_motor.h>
#include <Clock_1.h>
#include <UART_1.h>
#include <rx_rcvd.h>
#include <Hall_sensor_aliases.h>
#include <Hall_sensor.h>
#include <wheel_tick.h>
#include <Counter_1.h>
#include <tick_timeout.h>
#include <Timer_1.h>
#include <ShiftReg_1.h>
#include <Counter_2.h>
#include <throttle_update.h>
#include <Clock_2.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
