/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <LCD.h>
#include <Pin_button_aliases.h>
#include <Pin_button.h>
#include <inter_button.h>
#include <PWM_Motor.h>
#include <Pin_motor_aliases.h>
#include <Pin_motor.h>
#include <Clock_1.h>
#include <UART.h>
#include <rx_rcvd.h>
#include <Hall_sensor_aliases.h>
#include <Hall_sensor.h>
#include <wheel_tick.h>
#include <Counter_PID.h>
#include <tick_timeout.h>
#include <Timer_Wheel_Tick.h>
#include <Counter_Tick_Timeout.h>
#include <throttle_update.h>
#include <Clock_2.h>
#include <PWM_Servo.h>
#include <Pin_servo_aliases.h>
#include <Pin_servo.h>
#include <Clock_3.h>
#include <Vertical_sync_aliases.h>
#include <Vertical_sync.h>
#include <Horiz_sync_aliases.h>
#include <Horiz_sync.h>
#include <Comparator_aliases.h>
#include <Comparator.h>
#include <Camera_data_aliases.h>
#include <Camera_data.h>
#include <camera_frame_start.h>
#include <Trigger_aliases.h>
#include <Trigger.h>
#include <Timer_Row.h>
#include <Timer_Line_Begin.h>
#include <Line_begin_aliases.h>
#include <Line_begin.h>
#include <camera_comp_rise.h>
#include <Timer_Line_End.h>
#include <camera_comp_fall.h>
#include <Counter_Last_Row.h>
#include <Counter_First_Row.h>
#include <Line_end_aliases.h>
#include <Line_end.h>
#include <Comp_out_aliases.h>
#include <Comp_out.h>
#include <Horiz_out_aliases.h>
#include <Horiz_out.h>
#include <Vert_out_aliases.h>
#include <Vert_out.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
